name: Check PR Title
on:
  pull_request:
jobs:
  pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "^:[a-z_]+: .*"
          helpMessage: "Your PR title must start with a gitmoji and a space. More info: https://gitmoji.dev/"
