name: Lint
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
jobs:
  lint:
    uses: goravel/.github/.github/workflows/lint.yml@master
    secrets: inherit
  nilaway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - name: Install Nilaway
        run: go install go.uber.org/nilaway/cmd/nilaway@latest
      - name: Run Nilaway
        run: nilaway ./...