name: Mockery

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  mockery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Mockery
        run: |
          go install github.com/vektra/mockery/v2@v2.34.2

      - name: Generate Mocks for given directory
        run: |
          ~/go/bin/mockery --all --keeptree --dir=contracts
          ~/go/bin/mockery --all --keeptree --dir=database/gorm 

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update mocks"
