name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linux:
    strategy:
      matrix:
        go:
          - "stable"
          - "oldstable"
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql/mysql-server:latest
        env:
          MYSQL_DATABASE: goravel
          MYSQL_USER: goravel
          MYSQL_PASSWORD: Goravel(!)
          MYSQL_RANDOM_ROOT_PASSWORD: yes
        ports:
          - 3306:3306

      postgresql:
        image: postgres:latest
        env:
          TZ: Asia/Shanghai
          POSTGRES_DB: goravel
          POSTGRES_USER: goravel
          POSTGRES_PASSWORD: Goravel(!)
        ports:
          - 5432:5432

      sqlserver:
        image: mcmoe/mssqldocker:latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: Password!1234
          MSSQL_DB: goravel
          MSSQL_USER: goravel
          MSSQL_PASSWORD: Goravel(!)
        ports:
          - 1433:1433

      sqlite:
        image: nouchka/sqlite3:latest
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests with coverage
        run: go test -v -coverprofile="coverage.out" ./...
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          token: ${{ secrets.CODECOV }}

  windows:
    strategy:
      matrix:
        go:
          - "stable"
          - "oldstable"
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./... -short
