name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        go: [ '1.20', '1.19', '1.18' ]
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./...
